# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RYAN // ARTIFICIAL-RYAN
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Creator, Coder, Musician, Thinker. A digital universe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Artificial-Ryan.github.io" # the base hostname & protocol for your site
twitter_username: ArtificialRyan
github_username:  Artificial-Ryan

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - admin

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically excluded from
# the internal list of files to be processed, which includes items from the
# source directory as well as gems that ship with default files.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
