backend:
  name: github
  repo: Artificial-Ryan/Artificial-Ryan.github.io # The path to your GitHub repository
  branch: main # The branch to update
  auth_type: oauth
  client_id: Ov23liKqiq8XwThAvh14
  base_url: https://api.decapcms.org

media_folder: "assets/uploads" # Where media files will be stored
public_folder: "/assets/uploads" # The public-facing path to the media folder

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new documents
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
